In [1]:
!pip install bioinfokit

Requirement already satisfied: bioinfokit in c:\users\hp\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: matplotlib-venn in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.11.7)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (1.9.3)
Requirement already satisfied: textwrap3 in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.9.2)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (1.21.5)
Requirement already satisfied: statsmodels in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.13.2)
Requirement already satisfied: matplotlib in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (3.6.2)
Requirement already satisfied: seaborn in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.12.1)
Requirement already satisfied: scikit-learn in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (1.2.0)
Requirement already satisfied: tabulate in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.8.10)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (1.4.4)
Requirement already satisfied: adjustText in c:\users\hp\anaconda3\lib\site-packages (from bioinfokit) (0.7.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (4.25.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (22.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (3.0.9)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (9.3.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas->bioinfokit) (2022.7)
Requirement already satisfied: joblib>=1.1.1 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn->bioinfokit) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn->bioinfokit) (2.2.0)
Requirement already satisfied: patsy>=0.5.2 in c:\users\hp\anaconda3\lib\site-packages (from statsmodels->bioinfokit) (0.5.2)
Requirement already satisfied: six in c:\users\hp\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels->bioinfokit) (1.16.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv(r"D:\dataset\Wine.csv")
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [4]:
from sklearn.manifold import TSNE
from bioinfokit.visuz import cluster

In [5]:
x = df.iloc[:,:-1]
x

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
tsne = TSNE(n_components=2)
score = tsne.fit_transform(x)
score

array([[  5.254997  , -10.699653  ],
       [  5.748371  , -10.063413  ],
       [  6.6063347 , -12.490015  ],
       [  7.969169  , -15.001996  ],
       [  1.207723  ,  -2.9819524 ],
       [  7.632833  , -14.975427  ],
       [  6.9235315 , -13.986658  ],
       [  7.5770583 , -13.77272   ],
       [  5.1499166 , -10.211586  ],
       [  5.1471486 , -10.21494   ],
       [  7.791031  , -15.25855   ],
       [  6.830742  , -13.835403  ],
       [  7.1672325 , -14.247696  ],
       [  6.3355637 , -11.920617  ],
       [  7.9897738 , -15.328954  ],
       [  7.374866  , -14.062712  ],
       [  7.492799  , -13.509099  ],
       [  6.1346745 , -11.585791  ],
       [  8.069145  , -15.573862  ],
       [  2.9573133 ,  -5.8405914 ],
       [  1.9878803 ,  -4.220816  ],
       [  2.000928  ,  -3.7896755 ],
       [  5.0423303 , -10.004696  ],
       [  4.9873776 ,  -9.6176    ],
       [  2.8304396 ,  -5.9549766 ],
       [  2.7710552 ,  -5.3917537 ],
       [  6.6488376 , -12.667193  ],
       [  7.4603004 , -13.631237  ],
       [  3.7910786 ,  -7.191121  ],
       [  5.545769  ,  -9.768845  ],
       [  7.475296  , -13.626393  ],
       [  7.8462834 , -15.258866  ],
       [  4.897829  ,  -9.13505   ],
       [  7.049854  , -13.070684  ],
       [  5.6696935 , -11.099139  ],
       [  3.8436823 ,  -7.291485  ],
       [  3.4915547 ,  -6.4347315 ],
       [  6.099073  , -11.093658  ],
       [  5.270033  ,  -9.561712  ],
       [  1.5896978 ,  -3.7590287 ],
       [  2.314907  ,  -4.5971746 ],
       [  5.584298  ,  -9.754169  ],
       [  6.047815  , -10.900189  ],
       [  0.42178833,  -0.5988425 ],
       [  3.481489  ,  -6.5882535 ],
       [  5.6278567 , -10.8266945 ],
       [  5.8730426 , -10.369311  ],
       [  4.860502  ,  -9.033113  ],
       [  5.83482   , -10.274652  ],
       [  6.85247   , -13.458968  ],
       [  6.330905  , -11.923314  ],
       [  6.7871056 , -13.578905  ],
       [  6.6312146 , -12.583712  ],
       [  7.6100984 , -14.471663  ],
       [  5.2646403 , -10.569779  ],
       [  5.9723816 , -11.457317  ],
       [  4.606146  ,  -8.641399  ],
       [  7.2923174 , -13.400149  ],
       [  6.893767  , -13.905323  ],
       [ -3.8161528 ,   7.3472505 ],
       [  0.35991222,  -0.6276317 ],
       [ -6.059383  ,  10.670845  ],
       [ -1.1399064 ,   1.5460422 ],
       [ -6.5936418 ,  12.021816  ],
       [ -7.865432  ,  13.750119  ],
       [  0.04432115,  -0.5752536 ],
       [ -4.189604  ,   8.340748  ],
       [ -4.01889   ,   8.003243  ],
       [  1.6071883 ,  -3.301213  ],
       [  0.5961428 ,  -3.053493  ],
       [  3.229094  ,  -6.31668   ],
       [ -6.9696116 ,  12.305908  ],
       [ -5.24339   ,   9.653662  ],
       [  4.689216  ,  -8.937863  ],
       [  3.4617097 ,  -6.628027  ],
       [ -6.541739  ,  11.589911  ],
       [ -6.9840474 ,  12.953938  ],
       [ -5.2323413 ,   7.926162  ],
       [  1.288688  ,  -3.5979307 ],
       [ -5.760784  ,  10.05601   ],
       [ -8.010677  ,  14.935849  ],
       [  0.92022747,  -1.908108  ],
       [ -1.4961175 ,   1.3263206 ],
       [ -4.1191535 ,   7.640343  ],
       [ -4.256922  ,   7.1104813 ],
       [ -6.038682  ,  10.684779  ],
       [ -4.8140078 ,   8.433296  ],
       [ -2.7883818 ,   5.01884   ],
       [ -0.27768922,  -0.8179625 ],
       [ -1.7993407 ,   1.4956399 ],
       [ -4.8498526 ,   9.289431  ],
       [ -5.829847  ,  10.813448  ],
       [ -4.4414034 ,   8.6211    ],
       [ -7.991733  ,  14.835641  ],
       [ -7.3745184 ,  14.203816  ],
       [  4.1628485 ,  -7.8614297 ],
       [ -0.52401865,   2.368324  ],
       [ -6.2967234 ,  11.805097  ],
       [ -0.53253067,   0.14535227],
       [ -7.0268054 ,  12.436305  ],
       [  0.79166526,  -1.8404303 ],
       [ -2.788891  ,   5.0266433 ],
       [ -6.304251  ,  11.192571  ],
       [ -6.6898828 ,  12.208469  ],
       [ -0.41322947,  -0.38564909],
       [ -8.018562  ,  14.485166  ],
       [ -4.0906234 ,   7.9662876 ],
       [ -4.7643967 ,   8.886396  ],
       [ -7.7189927 ,  14.673139  ],
       [ -0.06361078,  -0.7854396 ],
       [ -3.217431  ,   4.8719225 ],
       [ -7.533259  ,  14.525603  ],
       [ -1.595859  ,   2.7559278 ],
       [ -6.2109156 ,  11.508044  ],
       [ -7.3428774 ,  13.020498  ],
       [ -6.7131114 ,  12.564386  ],
       [ -4.6699347 ,   8.499299  ],
       [ -7.9727163 ,  13.974046  ],
       [ -7.5663037 ,  13.34897   ],
       [ -2.7360158 ,   4.8768234 ],
       [ -1.2436161 ,   1.8993688 ],
       [ -6.1294365 ,   9.741212  ],
       [ -7.2261176 ,  13.789122  ],
       [ -7.035049  ,  13.35111   ],
       [ -7.008065  ,  13.355548  ],
       [ -7.4564414 ,  13.216444  ],
       [ -7.358567  ,  14.003562  ],
       [ -5.5085664 ,   9.961439  ],
       [ -7.805009  ,  14.070433  ],
       [ -2.464596  ,   4.1565795 ],
       [ -0.5669157 ,   2.0363028 ],
       [ -3.9044175 ,   6.531706  ],
       [ -3.0999222 ,   5.078708  ],
       [ -1.8163134 ,   3.0941727 ],
       [ -0.82842565,   0.59522516],
       [  0.44089404,  -1.3228625 ],
       [  1.112155  ,  -2.1205049 ],
       [ -4.5560694 ,   7.3598146 ],
       [ -2.4934072 ,   4.1382246 ],
       [ -2.2005923 ,   3.6039033 ],
       [ -1.946121  ,   3.0457942 ],
       [  2.2165332 ,  -4.03926   ],
       [ -4.3591933 ,   7.0465884 ],
       [ -3.2370803 ,   5.6609592 ],
       [  3.2684739 ,  -5.9374065 ],
       [  2.7453322 ,  -5.4414387 ],
       [ -6.4615645 ,  12.363954  ],
       [ -1.4813567 ,   1.7241634 ],
       [ -0.63291323,   0.69798535],
       [ -3.4673188 ,   5.5540695 ],
       [ -5.5151677 ,   7.8756413 ],
       [ -5.717085  ,   8.998199  ],
       [ -6.909246  ,  11.426336  ],
       [  0.11561019,  -0.2889705 ],
       [ -0.6965531 ,   1.2559311 ],
       [  1.2222672 ,  -2.3257775 ],
       [ -5.121836  ,   9.202546  ],
       [  3.30006   ,  -6.545365  ],
       [ -0.15289922,   0.34798965],
       [ -1.5549037 ,   2.0473702 ],
       [ -3.9856362 ,   7.2711067 ],
       [  0.5250663 ,  -0.5662047 ],
       [ -2.8837204 ,   4.493815  ],
       [  0.35663757,  -0.237037  ],
       [ -1.640363  ,   2.2755198 ],
       [ -4.0022163 ,   7.261842  ],
       [  0.67933875,  -1.2662439 ],
       [  0.02375852,  -1.0525014 ],
       [  1.7025933 ,  -3.2038376 ],
       [ -0.7539908 ,   1.8769742 ],
       [ -4.6327777 ,   7.640075  ],
       [ -5.254112  ,   9.755816  ],
       [ -0.37515905,   0.23130251],
       [  1.5552946 ,  -2.7650754 ],
       [  1.7292627 ,  -3.1680954 ],
       [  2.91514   ,  -5.499819  ],
       [  3.0939474 ,  -5.5945663 ],
       [ -3.0771272 ,   5.0932236 ]], dtype=float32)

In [9]:
cluster.tsneplot(score, colorlist=df['Customer_Segment'], figname="Wine_t-SNE")

# Diabetes Dataset

In [10]:
df = pd.read_csv(r"D:\dataset\diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df.iloc[:,:-1])
model

array([[-29.880531  ,  -0.06522568],
       [-11.986039  ,  -4.0879645 ],
       [-39.153004  ,  -3.7742994 ],
       ...,
       [ 24.446783  ,   6.975148  ],
       [-28.75854   , -12.680367  ],
       [-13.4789    ,  -3.0148342 ]], dtype=float32)

In [13]:
cluster.tsneplot(model, colorlist=df['Outcome'], figname='Diabetes_t-SNE')

# Iris Dataset

In [15]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
                 header=None)
df

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df.iloc[:,:-1])
model

array([[-23.611702 ,  10.089279 ],
       [-21.105064 ,   9.046296 ],
       [-21.186293 ,  10.187362 ],
       [-20.764452 ,   9.781459 ],
       [-23.761559 ,   9.79566  ],
       [-25.623129 ,   9.734678 ],
       [-21.346037 ,  10.572695 ],
       [-22.99371  ,   9.706161 ],
       [-20.021988 ,   9.809314 ],
       [-21.650875 ,   9.293126 ],
       [-25.059715 ,  10.335419 ],
       [-22.433823 ,   9.274111 ],
       [-20.869028 ,   9.277591 ],
       [-19.900421 ,  10.386554 ],
       [-26.27064  ,  10.623719 ],
       [-26.532549 ,  10.1326885],
       [-25.681154 ,  10.200215 ],
       [-23.708931 ,   9.909932 ],
       [-25.757885 ,  10.67189  ],
       [-24.812407 ,   9.538914 ],
       [-24.369915 ,  10.836553 ],
       [-24.478966 ,   9.4723835],
       [-21.47657  ,  11.338653 ],
       [-23.435173 ,   8.744777 ],
       [-22.58002  ,   8.404304 ],
       [-21.581211 ,   8.67268  ],
       [-23.320261 ,   9.131568 ],
       [-24.03713  ,  10.133366 ],
       [-23.582657 ,  10.412452 ],
       [-21.448423 ,   9.686137 ],
       [-21.439743 ,   9.066371 ],
       [-24.334223 ,  10.74492  ],
       [-25.847813 ,   9.503718 ],
       [-26.25072  ,  10.024484 ],
       [-21.650877 ,   9.293127 ],
       [-22.161978 ,  10.30236  ],
       [-24.80932  ,  10.951928 ],
       [-21.650875 ,   9.293127 ],
       [-20.131607 ,  10.1067505],
       [-23.291235 ,   9.855432 ],
       [-23.195946 ,  10.28602  ],
       [-19.585083 ,   9.201653 ],
       [-20.468542 ,  10.52514  ],
       [-23.847784 ,   8.785053 ],
       [-25.063387 ,   8.843074 ],
       [-20.844782 ,   9.269683 ],
       [-24.898712 ,   9.458169 ],
       [-20.947468 ,  10.143164 ],
       [-24.857267 ,  10.115869 ],
       [-22.57975  ,   9.920789 ],
       [ 10.932061 ,  -6.049247 ],
       [  9.644609 ,  -5.0433884],
       [ 11.332257 ,  -5.7586746],
       [  4.747397 ,  -4.5874686],
       [ 10.15867  ,  -5.051392 ],
       [  7.015442 ,  -4.174841 ],
       [  9.954726 ,  -4.383634 ],
       [  3.2794683,  -4.569614 ],
       [ 10.102787 ,  -5.509337 ],
       [  4.787364 ,  -4.942341 ],
       [  3.4379244,  -4.7333384],
       [  7.1926327,  -4.516881 ],
       [  4.8887763,  -3.152597 ],
       [  9.130795 ,  -4.1667285],
       [  4.543392 ,  -3.7376406],
       [  9.993059 ,  -5.819141 ],
       [  7.254906 ,  -3.8729637],
       [  5.541385 ,  -3.830038 ],
       [  8.526609 ,  -2.3987424],
       [  4.795371 ,  -4.1379385],
       [ 10.122967 ,  -3.0571046],
       [  6.2086225,  -3.5956247],
       [ 11.108989 ,  -3.8258867],
       [  8.769558 ,  -4.279019 ],
       [  8.941328 ,  -5.3169413],
       [  9.753395 ,  -5.6112657],
       [ 10.950048 ,  -5.573676 ],
       [ 12.004613 ,  -5.094567 ],
       [  8.376612 ,  -4.182981 ],
       [  4.106458 ,  -3.8166983],
       [  4.4004073,  -4.3298354],
       [  4.1571054,  -4.242352 ],
       [  5.300062 ,  -3.8843937],
       [ 11.4476   ,  -2.8473022],
       [  6.9953732,  -3.6102855],
       [  9.254815 ,  -3.7629597],
       [ 10.674815 ,  -5.5957246],
       [  8.296404 ,  -2.5582376],
       [  6.1855106,  -4.442194 ],
       [  5.0260477,  -4.518389 ],
       [  5.869108 ,  -4.788685 ],
       [  8.9137945,  -4.3287945],
       [  5.3588624,  -3.919166 ],
       [  3.3297336,  -4.5536237],
       [  5.8207607,  -4.4310346],
       [  6.4298334,  -4.402679 ],
       [  6.378192 ,  -4.308863 ],
       [  8.243853 ,  -4.8550687],
       [  3.1567962,  -4.453796 ],
       [  5.914273 ,  -4.2276073],
       [ 16.261974 ,  -2.4251354],
       [ 11.396983 ,  -2.0492883],
       [ 17.23743  ,  -3.9570007],
       [ 14.197437 ,  -3.9492724],
       [ 15.854134 ,  -3.4461334],
       [ 18.443611 ,  -4.7026963],
       [  6.2313414,  -2.4383695],
       [ 18.183567 ,  -4.118299 ],
       [ 17.184614 ,  -2.8619955],
       [ 17.214436 ,  -4.78813  ],
       [ 14.187964 ,  -3.004878 ],
       [ 13.498501 ,  -3.6016624],
       [ 15.70153  ,  -3.8423667],
       [ 11.273029 ,  -1.6710807],
       [ 11.953413 ,  -1.506452 ],
       [ 15.011546 ,  -2.695573 ],
       [ 14.452502 ,  -3.9164562],
       [ 18.097609 ,  -5.3256383],
       [ 18.821022 ,  -4.6966352],
       [  9.986785 ,  -1.9669442],
       [ 16.481651 ,  -3.7833002],
       [ 11.0926075,  -1.6992574],
       [ 18.635332 ,  -4.651791 ],
       [ 11.493236 ,  -3.4838972],
       [ 16.198872 ,  -3.6478424],
       [ 17.677677 ,  -4.0100646],
       [ 10.985528 ,  -3.3883648],
       [ 10.801357 ,  -3.099197 ],
       [ 14.929813 ,  -3.8618734],
       [ 17.77134  ,  -3.689483 ],
       [ 18.11     ,  -4.07742  ],
       [ 18.072546 ,  -5.320016 ],
       [ 15.084431 ,  -3.7818363],
       [ 11.689373 ,  -3.8262289],
       [ 12.803105 ,  -3.348603 ],
       [ 18.089754 ,  -4.627546 ],
       [ 15.717559 ,  -2.3802934],
       [ 14.363278 ,  -3.859598 ],
       [ 10.470892 ,  -3.0489252],
       [ 15.760053 ,  -3.9253983],
       [ 15.997376 ,  -3.2712119],
       [ 15.209012 ,  -3.0743976],
       [ 11.398715 ,  -2.0499368],
       [ 16.638895 ,  -3.6975267],
       [ 16.303123 ,  -3.0648115],
       [ 15.092388 ,  -3.113184 ],
       [ 11.938377 ,  -3.205494 ],
       [ 14.189379 ,  -3.2834003],
       [ 15.228045 ,  -2.2259781],
       [ 11.160728 ,  -2.5086763]], dtype=float32)

In [18]:
cluster.tsneplot(model, colorlist=df[4], figname='iris_data_t-SNE')